# Generated by Django 3.2.13 on 2022-08-03 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classrooms', '0003_auto_20220803_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroomsubject',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='classrooms.classroom'),
        ),
        migrations.AlterField(
            model_name='classroomsubject',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pengajar', to=settings.AUTH_USER_MODEL),
        ),
    ]
