# Generated by Django 3.2.13 on 2022-08-03 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0004_auto_20220803_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroomsubject',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
