# Generated by Django 3.2.13 on 2022-08-03 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0005_classroomsubject_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroomsubject',
            name='slug',
        ),
    ]
