# Generated by Django 3.2.13 on 2022-09-08 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0008_alter_classroomtimetable_grade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroomtimetable',
            options={'ordering': ('-id',), 'verbose_name_plural': 'Jadwal Kelas'},
        ),
    ]
