# Generated by Django 3.2.13 on 2022-09-12 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0010_classroomsubject_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroomattendance',
            name='token',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
