# Generated by Django 3.2.13 on 2022-09-12 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0011_classroomattendance_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroomattendance',
            name='status',
            field=models.CharField(choices=[('ALPHA', 'alpha'), ('HADIR', 'hadir'), ('IJIN', 'ijin')], default='ALPHA', max_length=20),
        ),
        migrations.AlterField(
            model_name='classroomattendance',
            name='timetable',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='classrooms.classroomtimetable'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classroomattendance',
            name='token',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
    ]
