# Generated by Django 3.2.13 on 2022-09-07 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0002_remove_leave_attendance_scheduled'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='attendance_scheduled',
            field=models.ManyToManyField(blank=True, to='attendances.AttendanceTimetable'),
        ),
    ]
