# Generated by Django 3.2.13 on 2022-09-12 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0003_leave_attendance_scheduled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='attachment',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
